---
# Changing Password for RAR JVMs
- block:
  - name: Getting JVM Name
    shell: "ls -l /application/IBM/WASProfiles/servers/ | grep -w {{jvmName}}-inst[0-9][0-9] | egrep '^d' | awk '{print $(NF)}' |grep inst0{{inst}}"
    register: shellOut
  - name: Changing Password for {{jvmName|upper}}-INST0{{inst|upper}}
    shell: |
      rtmadm_NEW_PWD={{ rtmadm_pass }}
      cogadm_NEW_PWD={{ cogadm_pass }}
      rwsuser_NEW_PWD={{ rwsuser_pass }}
      rwsadm_NEW_PWD={{ rwsadm_pass }}
      for j in `find /application/IBM/WASProfiles/servers/{{ shellOut.stdout }} -name 'datasource_config.xml' `; do
        if [ -f $j ]
        then 
          cp $j $j.bak_`date +%d%b%Y%H%M%S`;
          if [ -n {{ rtmadm_pass }} ]
          then
            rtmadm_NEW_PWD={{ rtmadm_pass }};
            for i in `grep -n rtmadm $j | grep -v '!--' |awk -F : '{print $1}'`; do
              rtmpassline=`grep -n 'user="rtmadm"' $j | grep -v '!--' |grep ^$i`
              old_pwd=`echo $rtmpassline|awk -F "password" '{print $NF}'|awk -F '"' '{print $2}'`
              rtmTempLine=`echo $rtmpassline| sed "s/$old_pwd/$rtmadm_NEW_PWD/g"`
              sed -i "${i}d" $j;
              sed  -i "${i}i ${rtmTempLine}" $j;
              sed -i "s/^$i://g" $j
            done
          fi;
          if [ -n {{ cogadm_pass }} ]
          then
            cogadm_NEW_PWD={{ cogadm_pass }}
            for i in `grep -n cogadm $j | grep -v '!--' | awk -F : '{print $1}'`; do
              cogpassline=`grep -n 'user="cogadm"' $j|  grep -v '!--' |grep ^$i`
              old_pwd=`echo $cogpassline|awk -F "password" '{print $NF}'|awk -F '"' '{print $2}'`
              cogTempLine=`echo $cogpassline|sed "s/$old_pwd/$cogadm_NEW_PWD/g"`;
              sed -i "${i}d" $j;
              sed  -i "${i}i ${cogTempLine}" $j;
              sed -i "s/^$i://g" $j
            done
          fi;
          if [ -n {{ cogadm_pass }} ]
          then
            rwsuser_NEW_PWD={{ rwsuser_pass }}
            for i in `grep -n rwsuser $j| grep -v '!--' | awk -F : '{print $1}'`; do
              rwsuserpassline=`grep -n 'user="rwsuser"' $j|  grep -v '!--' |grep ^$i`
              old_pwd=`echo $rwsuserpassline |awk -F "password" '{print $NF}'|awk -F '"' '{print $2}'`
              rwsuserTempLine=`echo $rwsuserpassline|sed "s/$old_pwd/$rwsuser_NEW_PWD/g"`;
              sed -i "${i}d" $j;
              sed  -i "${i}i ${rwsuserTempLine}" $j;
              sed -i "s/^$i://g" $j
            done
          fi;
          if [ -n {{ cogadm_pass }} ]
          then
            rwsadm_NEW_PWD={{ rwsadm_pass }}
            for i in `grep -n rwsadm $j | grep -v '!--' | awk -F : '{print $1}'`; do
              rwsadmpassline=`grep -n 'user="rwsadm"' $j|  grep -v '!--' |grep ^$i`
              old_pwd=`echo $rwsadmpassline |awk -F "password" '{print $NF}'|awk -F '"' '{print $2}'`
              rwsadmTempLine=`echo $rwsadmpassline|sed "s/$old_pwd/$rwsadm_NEW_PWD/g"`;
              sed -i "${i}d" $j;
              sed  -i "${i}i ${rwsadmTempLine}" $j;
              sed -i "s/^$i://g" $j
            done
          fi;
          echo $j 'file has been updated' ;
        fi;
      done
    register: changeoutput

  - name: Password Change Status
    debug:
      msg: "{{ changeoutput.stdout }}"
  when: '(jvmName is defined and jvmName == "rar")'