---
- block:
    - block:
        - set_fact:
            rar_loop: "{{reflexis_rar_jvm_count|int}}"
        - include_tasks: pwdChangeUtil.ansible.yml
          vars:
            - inst: "{{item|int}}"
            - control: change
            - jvmName: rar
          with_sequence: start=1 end={{rar_loop|int if rar_loop|int > 0 else rar_loop}}
          when: rar_loop is defined
      when: '(reflexis_rar_jvm_count is defined) and (reflexis_rar_jvm_count|int>0)'
      tags: changeRARpwd
  when: '(WAS_DEPLOY_NODE is defined and WAS_DEPLOY_NODE==true)'
  tags: passwordChangeForRAR
